//! Generates and verifies the Crash Capsule specification corpus.
//!
//! The corpus is *generated* rather than hand-written, and the same function that writes it is
//! the one the conformance test compares against the committed files. That makes the corpus a
//! diff-visible artefact: any encoder change that moves a byte, and any registry change that
//! adds a field, shows up as a corpus diff in the same pull request instead of silently
//! diverging from other implementations.
//!
//! Run `cargo run -p cc-vectors` to regenerate; CI fails if the working tree then differs.

#![deny(missing_docs)]

pub mod cases;

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use sha2::{Digest, Sha256};

/// Directory, relative to the repository root, holding everything this crate generates.
pub const SPECIFICATION_DIR: &str = "specification";

/// Absolute path of the repository root, derived from this crate's manifest location.
#[must_use]
pub fn repository_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .unwrap_or_else(|| Path::new("."))
        .to_path_buf()
}

fn sha256_hex(bytes: &[u8]) -> String {
    hex::encode(Sha256::digest(bytes))
}

/// Builds every generated file, keyed by its path relative to the repository root.
///
/// Values are exact file contents, so the caller can either write them or compare them.
#[must_use]
pub fn generated_files() -> BTreeMap<PathBuf, Vec<u8>> {
    let mut files = BTreeMap::new();
    let dir = Path::new(SPECIFICATION_DIR);

    let mut canonical_manifest = String::from(
        "# Generated by `cargo run -p cc-vectors`. Do not edit.\n\
         # name\tbytes\tsha256\tstrict-fingerprint\tfamily-fingerprint\tnote\n",
    );
    for case in cases::canonical_cases() {
        let bytes = case.capsule.encode();
        let _ = writeln!(
            canonical_manifest,
            "{}\t{}\t{}\t{}\t{}\t{}",
            case.name,
            bytes.len(),
            sha256_hex(&bytes),
            hex::encode(case.capsule.fingerprints.strict),
            hex::encode(case.capsule.fingerprints.family),
            case.note,
        );
        files.insert(
            dir.join("test-vectors/canonical")
                .join(format!("{}.cbor", case.name)),
            bytes,
        );
    }
    files.insert(
        dir.join("test-vectors/canonical/manifest.tsv"),
        canonical_manifest.into_bytes(),
    );

    let mut malformed_manifest = String::from(
        "# Generated by `cargo run -p cc-vectors`. Do not edit.\n\
         # Every input here must be rejected by a conforming decoder.\n\
         # name\tbytes\tsha256\treason\n",
    );
    for case in cases::malformed_cases() {
        let _ = writeln!(
            malformed_manifest,
            "{}\t{}\t{}\t{}",
            case.name,
            case.bytes.len(),
            sha256_hex(&case.bytes),
            case.note,
        );
        files.insert(
            dir.join("test-vectors/malformed")
                .join(format!("{}.cbor", case.name)),
            case.bytes,
        );
    }
    files.insert(
        dir.join("test-vectors/malformed/manifest.tsv"),
        malformed_manifest.into_bytes(),
    );

    let mut fingerprint_manifest = String::from(
        "# Generated by `cargo run -p cc-vectors`. Do not edit.\n\
         # Hash the material bytes with SHA-256 to obtain the fingerprint.\n\
         # name\tmaterial-sha256\tfingerprint\tsignature\n",
    );
    for case in cases::fingerprint_cases() {
        let _ = writeln!(
            fingerprint_manifest,
            "{}\t{}\t{}\t{}",
            case.name,
            sha256_hex(&case.material),
            hex::encode(case.fingerprint),
            cc_fingerprint::signature(&case.fingerprint),
        );
        files.insert(
            dir.join("test-vectors/fingerprint")
                .join(format!("{}.material.cbor", case.name)),
            case.material,
        );
    }
    files.insert(
        dir.join("test-vectors/fingerprint/manifest.tsv"),
        fingerprint_manifest.into_bytes(),
    );

    files.insert(
        dir.join("privacy-registry.md"),
        privacy_registry_markdown().into_bytes(),
    );

    files
}

/// Renders the human-readable privacy registry from the machine-readable one.
///
/// `registry.toml` is normative; this document exists so reviewers can see the classification of
/// every field without reading TOML, and it is regenerated rather than maintained by hand
/// precisely so the two cannot drift.
#[must_use]
pub fn privacy_registry_markdown() -> String {
    let source = include_str!("../../../specification/registry.toml");
    let registry: toml::Value =
        toml::from_str(source).unwrap_or(toml::Value::Table(toml::map::Map::new()));

    let mut out = String::new();
    out.push_str("# Crash Capsule privacy registry\n\n");
    out.push_str(
        "Generated from `specification/registry.toml` by `cargo run -p cc-vectors`. Do not edit.\n\n",
    );
    out.push_str(&format!(
        "Schema version: {}.{}\n\n",
        cc_schema::SCHEMA_MAJOR,
        cc_schema::SCHEMA_MINOR
    ));
    out.push_str(
        "A field's effective class is `max(schema minimum class, producer declared class)`. A \
         producer may raise a classification; it can never lower one.\n\n",
    );

    out.push_str("## Classes\n\n| Class | Meaning |\n| --- | --- |\n");
    if let Some(classes) = registry.get("class").and_then(toml::Value::as_array) {
        for class in classes {
            let id = class
                .get("id")
                .and_then(toml::Value::as_integer)
                .unwrap_or(0);
            let description = class
                .get("description")
                .and_then(toml::Value::as_str)
                .unwrap_or_default();
            let _ = writeln!(out, "| P{id} | {description} |");
        }
    }

    out.push_str("\n## Profiles\n\n| Profile | Id | Target bytes | Hard limit | Max class |\n");
    out.push_str("| --- | --- | --- | --- | --- |\n");
    for spec in cc_schema::PROFILES {
        let _ = writeln!(
            out,
            "| `{}` | {} | {} | {} | P{} |",
            spec.name, spec.id, spec.target_bytes, spec.max_bytes, spec.max_class
        );
    }

    out.push_str("\n## Fields\n\n| Path | Key | Type | Class | Required | Description |\n");
    out.push_str("| --- | --- | --- | --- | --- | --- |\n");
    if let Some(fields) = registry.get("fields").and_then(toml::Value::as_array) {
        for field in fields {
            let get = |name: &str| field.get(name).and_then(toml::Value::as_str).unwrap_or("");
            let key = field
                .get("key")
                .and_then(toml::Value::as_integer)
                .unwrap_or(0);
            let required = field
                .get("required")
                .and_then(toml::Value::as_bool)
                .unwrap_or(false);
            let _ = writeln!(
                out,
                "| `{}` | {} | {} | {} | {} | {} |",
                get("path"),
                key,
                get("type"),
                get("class"),
                if required { "yes" } else { "no" },
                get("description"),
            );
        }
    }

    out.push_str("\n## Evidence kinds\n\n| Kind | Id | Minimum class |\n| --- | --- | --- |\n");
    for (id, name, floor) in cc_schema::EVIDENCE_KINDS {
        let _ = writeln!(out, "| `{name}` | {id} | P{floor} |");
    }

    out.push_str(
        "\n## Never collected by default\n\n\
         Serial numbers, machine UUIDs, motherboard identifiers, MAC addresses, IP addresses, \
         SSIDs, hostnames, DNS names, URLs, argv, environment variables, the current working \
         directory, file contents, process memory and full journals. Core dumps are P4 and are \
         referenced by hash, never embedded in a transported capsule.\n",
    );

    out
}
