//! Generates wire keys, profile budgets and privacy floors from
//! `specification/registry.toml` so the registry and the implementation cannot drift.
//!
//! A malformed registry must stop the build, so this script panics rather than degrading.

#![allow(clippy::expect_used, clippy::panic, clippy::unwrap_used)]

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::PathBuf;

const REGISTRY: &str = "../../specification/registry.toml";

fn main() {
    println!("cargo:rerun-if-changed={REGISTRY}");

    let text = std::fs::read_to_string(REGISTRY).unwrap_or_else(|e| {
        panic!("cannot read {REGISTRY}: {e}");
    });
    let registry: toml::Table = text
        .parse()
        .unwrap_or_else(|e| panic!("{REGISTRY} is not valid TOML: {e}"));

    let mut out = String::new();
    out.push_str("// @generated by build.rs from specification/registry.toml. Do not edit.\n\n");

    let major = int(&registry, "schema_major");
    let minor = int(&registry, "schema_minor");
    writeln!(out, "/// Incompatible schema generation.").unwrap();
    writeln!(out, "pub const SCHEMA_MAJOR: u64 = {major};").unwrap();
    writeln!(out, "/// Additive schema revision.").unwrap();
    writeln!(out, "pub const SCHEMA_MINOR: u64 = {minor};\n").unwrap();

    emit_keys(&mut out, &registry);
    emit_floors(&mut out, &registry);
    emit_profiles(&mut out, &registry);
    emit_table(&mut out, &registry, "source_kind", "SOURCE_KINDS");
    emit_table(&mut out, &registry, "failure_class", "FAILURE_CLASSES");
    emit_table(&mut out, &registry, "category", "CATEGORIES");
    emit_evidence_kinds(&mut out, &registry);

    let dest = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("registry.rs");
    std::fs::write(&dest, out).unwrap_or_else(|e| panic!("cannot write {}: {e}", dest.display()));
}

fn int(table: &toml::Table, key: &str) -> i64 {
    table
        .get(key)
        .and_then(toml::Value::as_integer)
        .unwrap_or_else(|| panic!("registry key `{key}` missing or not an integer"))
}

fn array<'a>(registry: &'a toml::Table, key: &str) -> &'a [toml::Value] {
    registry
        .get(key)
        .and_then(toml::Value::as_array)
        .map(Vec::as_slice)
        .unwrap_or_else(|| panic!("registry array `{key}` missing"))
}

fn entry<'a>(value: &'a toml::Value, key: &str) -> &'a toml::Value {
    value
        .get(key)
        .unwrap_or_else(|| panic!("registry entry missing `{key}`: {value}"))
}

fn string(value: &toml::Value, key: &str) -> String {
    entry(value, key)
        .as_str()
        .unwrap_or_else(|| panic!("registry entry `{key}` is not a string"))
        .to_owned()
}

fn integer(value: &toml::Value, key: &str) -> i64 {
    entry(value, key)
        .as_integer()
        .unwrap_or_else(|| panic!("registry entry `{key}` is not an integer"))
}

fn class_id(name: &str) -> u8 {
    match name {
        "P0" => 0,
        "P1" => 1,
        "P2" => 2,
        "P3" => 3,
        "P4" => 4,
        other => panic!("unknown privacy class `{other}`"),
    }
}

fn ident(s: &str) -> String {
    s.replace(['-', '.', '/'], "_").to_uppercase()
}

/// Emits `keys::<struct>::<FIELD>` constants, one module per registry path prefix.
fn emit_keys(out: &mut String, registry: &toml::Table) {
    let mut groups: BTreeMap<String, Vec<(String, i64, String)>> = BTreeMap::new();
    for field in array(registry, "field") {
        let path = string(field, "path");
        let (group, name) = path
            .split_once('.')
            .unwrap_or_else(|| panic!("field path `{path}` must be `group.field`"));
        let key = integer(field, "key");
        let siblings = groups.entry(group.to_owned()).or_default();
        assert!(
            !siblings.iter().any(|(_, existing, _)| *existing == key),
            "duplicate key {key} in map `{group}` (field `{path}`)"
        );
        siblings.push((ident(name), key, string(field, "description")));
    }

    writeln!(
        out,
        "/// Integer keys used on the wire, grouped by containing map."
    )
    .unwrap();
    writeln!(out, "pub mod keys {{").unwrap();
    for (group, fields) in groups {
        writeln!(out, "    /// Keys of the `{group}` map.").unwrap();
        writeln!(out, "    pub mod {} {{", group.replace('-', "_")).unwrap();
        for (name, key, description) in fields {
            writeln!(out, "        /// {description}").unwrap();
            writeln!(out, "        pub const {name}: u64 = {key};").unwrap();
        }
        writeln!(out, "    }}").unwrap();
    }
    writeln!(out, "}}\n").unwrap();
}

fn emit_floors(out: &mut String, registry: &toml::Table) {
    let mut rows: Vec<(String, u8, bool)> = array(registry, "field")
        .iter()
        .map(|f| {
            (
                string(f, "path"),
                class_id(&string(f, "class")),
                entry(f, "required").as_bool().unwrap_or(false),
            )
        })
        .collect();
    rows.sort();

    writeln!(
        out,
        "/// `(field path, minimum privacy class, required)` for every standard field."
    )
    .unwrap();
    writeln!(
        out,
        "pub const FIELDS: &[(&str, u8, bool)] = &[\n{}];\n",
        rows.iter()
            .map(|(p, c, r)| format!("    (\"{p}\", {c}, {r}),\n"))
            .collect::<String>()
    )
    .unwrap();
}

fn emit_profiles(out: &mut String, registry: &toml::Table) {
    let rows: String = array(registry, "profile")
        .iter()
        .map(|p| {
            format!(
                "    ProfileSpec {{ id: {}, name: \"{}\", target_bytes: {}, max_bytes: {}, max_class: {} }},\n",
                integer(p, "id"),
                string(p, "name"),
                integer(p, "target_bytes"),
                integer(p, "max_bytes"),
                class_id(&string(p, "max_class")),
            )
        })
        .collect();
    writeln!(
        out,
        "/// Size and privacy budgets for every capsule profile."
    )
    .unwrap();
    writeln!(out, "pub const PROFILES: &[ProfileSpec] = &[\n{rows}];\n").unwrap();
}

fn emit_table(out: &mut String, registry: &toml::Table, key: &str, name: &str) {
    let rows: String = array(registry, key)
        .iter()
        .map(|v| format!("    ({}, \"{}\"),\n", integer(v, "id"), string(v, "name")))
        .collect();
    writeln!(out, "/// Registered `{key}` values as `(id, name)`.").unwrap();
    writeln!(out, "pub const {name}: &[(u64, &str)] = &[\n{rows}];\n").unwrap();
}

fn emit_evidence_kinds(out: &mut String, registry: &toml::Table) {
    let rows: String = array(registry, "evidence_kind")
        .iter()
        .map(|v| {
            format!(
                "    ({}, \"{}\", {}),\n",
                integer(v, "id"),
                string(v, "name"),
                class_id(&string(v, "class")),
            )
        })
        .collect();
    writeln!(
        out,
        "/// Registered evidence kinds as `(id, name, minimum privacy class)`."
    )
    .unwrap();
    writeln!(
        out,
        "pub const EVIDENCE_KINDS: &[(u64, &str, u8)] = &[\n{rows}];\n"
    )
    .unwrap();
}
